In [1]:
import numpy as np

In [4]:
a= [1,1,1,2,2,3]
np.bincount(a)

array([0, 3, 2, 1], dtype=int64)

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
text = ['我 爱 你 好 吗','一 点 都 不 好']
vectorizer=TfidfVectorizer()  #定义了一个类的实例
X=vectorizer.fit_transform(text)

ValueError: empty vocabulary; perhaps the documents only contain stop words

In [15]:

from sklearn.feature_extraction.text import TfidfVectorizer
document = ["I have a pen.",
            "I have an apple."]
tfidf_model = TfidfVectorizer().fit(document)
sparse_result = tfidf_model.transform(document) 

In [16]:

print(sparse_result.todense())   

[[0.         0.         0.57973867 0.81480247]
 [0.6316672  0.6316672  0.44943642 0.        ]]


In [17]:
print(X.todense())   

[[0. 1.]
 [1. 0.]]


In [21]:
import jieba
text = """我是一条天狗呀！
我把月来吞了，
我把日来吞了，
我把一切的星球来吞了，
我把全宇宙来吞了。
我便是我了！"""
sentences = text.split()
sent_words = [list(jieba.cut(sent0)) for sent0 in sentences]
document = [" ".join(sent0) for sent0 in sent_words]
print(document)

['我 是 一条 天狗 呀 ！', '我 把 月 来 吞 了 ，', '我 把 日来 吞 了 ，', '我 把 一切 的 星球 来 吞 了 ，', '我 把 全宇宙 来 吞 了 。', '我 便是 我 了 ！']


In [24]:
tfidf_model = TfidfVectorizer().fit(document)
print(tfidf_model.vocabulary_)
# {'一条': 1, '天狗': 4, '日来': 5, '一切': 0, '星球': 6, '全宇宙': 3, '便是': 2}
sparse_result = tfidf_model.transform(document)
print(sparse_result.todense())

{'一条': 1, '天狗': 4, '日来': 5, '一切': 0, '星球': 6, '全宇宙': 3, '便是': 2}
[[0.         0.70710678 0.         0.         0.70710678 0.
  0.        ]
 [0.         0.         0.         0.         0.         0.
  0.        ]
 [0.         0.         0.         0.         0.         1.
  0.        ]
 [0.70710678 0.         0.         0.         0.         0.
  0.70710678]
 [0.         0.         0.         1.         0.         0.
  0.        ]
 [0.         0.         1.         0.         0.         0.
  0.        ]]


In [ ]:
# 我爱你了
# 我真的爱你
我 爱 你 真 的 了
111001
111110